apiVersion: v1
kind: Pod
metadata:
  name: example-pod
spec:
  containers:
  - name: example-container
    image: example-image
    resources:
      requests:
        cpu: "2"
        memory: "2Gi"
      limits:
        memory: "2Gi"
